services:
   webapp:
      depends_on:
         database_postgres:
            condition: service_healthy
         phpPgAdmin:
            condition: service_healthy
      build: webapp/
      ports:
         - "30000-39999:80"
         - "30000-39999:443"
      volumes:
         - type: bind
           source: ../webapp_html/
           target: /var/www/html
         - type: bind
           source: ../etc/letsencrypt
           target: /etc/letsencrypt
      restart: unless-stopped
      networks:
         - frontend_bridge
         - database_network_default
   certbot:
      image: certbot/certbot:v1.7.0
      volumes:
         - type: bind
           source: ../webapp_html/
           target: /var/www/html
         - type: bind
           source: ../etc/letsencrypt
           target: /etc/letsencrypt
      command: ["--version"]
   dockerssl:
      build: dockerssl/
      volumes:
         - type: bind
           source: ../webapp_html/
           target: /var/www/html
         - type: bind
           source: ../etc/ssl
           target: /etc/ssl
   database_postgres:
      build: database/
      volumes:
         - db-store:/var/lib/postgresql/data
      environment:
         TZ: Asia/Tokyo
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      restart: always
      networks:
         - database_network_default
      healthcheck:
         test: psql -U postgres --list
         interval: 1s
         timeout: 1s
         retries: 3
         start_period: 1s
   phpPgAdmin:
      depends_on:
         database_postgres:
            condition: service_healthy
      image: dpage/pgadmin4:latest
      ports:
         - "30000-39999:80"
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      restart: unless-stopped
      volumes:
         - pgadmin-store:/var/lib/pgadmin
      networks:
         - frontend_bridge
         - database_network_default
      healthcheck:
         test: wget -O - http://localhost:80/misc/ping
         interval: 1s
         timeout: 1s
         retries: 10
         start_period: 10s
volumes:
   db-store:
   pgadmin-store:
networks:
   frontend_bridge:
      external: true
   database_network_default:
