name: Docker Build CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: docker-compose
      run: docker build . --tag my-image-name:$(date +%s)
